# required
[[plugins]]
repo = 'Shougo/dein.vim'

# completion
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

# Syntax checker
[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.vim/nvim/bundles/ale/settings.vim'

# statusline plugin
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'source ~/.vim/nvim/bundles/vim-airline/settings.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# file tree
[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
hook_add = 'source ~/.vim/nvim/bundles/nerdtree/settings.vim'

# color scheme
[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = 'source ~/.vim/nvim/bundles/colors/tender/settings.vim'

